version: '3.7'

services:
  world:
    build:
      context: .
      args:
        MINECRAFT_VERSION: 1.18.1
    image: minecraft-mcvicaria
    volumes:
      - "C:\\Users\\dwmcv\\.aws:/root/.aws"
    ports:
      - "25565:25565"
      - "25575:25575"
    command: bash ./bin/run_server.bash
    environment:
      MINECRAFT_VERSION: 1.18.1
      WORLD_NAME: Equestria
      MCRCON_PWD: password
